# sets up java, maven and gpg
# sets up settings.xml in such a way that the build/deploy works
# releases the project with specified version
# deploys it to the sonatype staging repo
name: Release and deploy to Sonatype staging repo
env:
  GITHUB_PAT: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  DEBUG_REPO_SECRET: ${{ secrets.DEBUG_REPO_SECRET }}
  DEBUG_ORG_SECRET: ${{ secrets.DEBUG_ORG_SECRET }}
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (such as 2.3.13)'
        required: true
        type: string
      next_snapshot_version:
        description: 'Next SNAPSHOT version (such as 2.4-SNAPSHOT)'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
    secrets:
      QUDTLIB_BOT_GITHUB_TOKEN:
        required: true
      MAVEN_USERNAME:
        required: true
      MAVEN_CENTRAL_TOKEN:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true

jobs:
  build:
    # setting the environment on the job is mandatory, otherwise it cannot access environment secrets.
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug secrets
        run: |
          echo Just to be sure, we check if we have access to the environment secrets:
          echo If line following this paragraph says, 'maven username: ***', it indicates that we can access
          echo environment secrets. If it says 'maven username:', we do not have access and the build will
          echo not work.
          echo 
          echo maven username: ${MAVEN_USERNAME}

      # check if a tag already exists for the version we want to publish - in that case the workflow
      # will fail later, so let us make it fail fast
      - name: Check if tag ${{ inputs.release_version }} exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
      - name: Fail if tag ${{ inputs.release_version }} exists
        if: steps.checkTag.outputs.exists == 'true'
        run: |
          echo Tag ${{ inputs.release_version }} already exists, release aborted >> $GITHUB_STEP_SUMMARY
          exit 1

      # Set up java with maven cache
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # import the secret key
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME  # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN  # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}  # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase
          cache: 'maven'

      - name: list GPG keys
        run: gpg --list-keys

      # configure git
      - name: setup git config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "<>"

      # because we protect the main branch, the action cannot push to the repository
      # Therefore, we create a branch for the release, and if the release succeeds, we will
      # submit a pull request
      - name: create branch for this release
        run: |
          BRANCH_NAME=release-$version-$(date +%s)
          git checkout --track -b $BRANCH_NAME
        env:
          version: ${{ inputs.release_version }}

      # Update changelog unreleased section with new version
      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ inputs.release_version }}
          operation: release

      # Apply formatting (changelog was touched)
      - name: Apply format using spotless:apply
        run: mvn spotless:apply -DspotlessFiles='.*CHANGELOG.md'

      # Commit changes
      - name: Commit CHANGELOG.md and package.json changes and create tag
        run: |
          git add "CHANGELOG.md"
          git commit -m "Update CHANGELOG.md for release ${{ inputs.release_version }}"

      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
        run: |
          git push origin

      # build and deploy to staging
      - name: Build with Maven, deploying to sonatype staging repo
        run: mvn -e -X -B release:clean release:prepare release:perform -DreleaseVersion=${{ inputs.release_version }} -DdevelopmentVersion=${{ inputs.next_snapshot_version }} -Darguments=-Dgpg.passphrase="$MAVEN_GPG_PASSPHRASE"
        env:
          password: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      # create the pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
          title: Release ${{ inputs.release_version }}
          base: 'main'
          branch: ${{ env.BRANCH_NAME }}
          body: |
            Automated release through workflow: '${{ github.workflow }}'
            Triggered by: ${{ github.triggering_actor }}
            Version: ${{ inputs.release_version }}
            Next development version: $${ inputs.next_snapshot_version }}

      # print the summary
      - name: Print summary
        run: echo "Release ${{ inputs.release_version }} deployed to sonatype staging repo. Please go there, close the repo and publish it." >> $GITHUB_STEP_SUMMARY
